# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install nginx python3-dev build-essential libpcre3 libpcre3-dev

WORKDIR /Intectainment

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python setup.py

COPY . .
RUN mv deploy/* .
RUN mv nginx.conf /etc/nginx

EXPOSE 80

RUN chmod +x ./start.sh
CMD ["./start.sh"]
