# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

RUN apt-get clean \
    && apt-get -y update

WORKDIR /Intectainment

COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

COPY . .

EXPOSE 80

CMD [ "python3", "run.py" ]
